# Generated by Django 4.1.1 on 2022-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="DeviceR",
            field=models.IntegerField(null=True),
        ),
    ]
