# Generated by Django 4.1.1 on 2022-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_customuser_devicer"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="DeviceR",),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
