# Generated by Django 4.1.1 on 2022-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_remove_customuser_devicer_customuser_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="address", field=models.TextField(),
        ),
    ]
