# Generated by Django 4.1.1 on 2022-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aduino",
            name="devicer",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
