# Generated by Django 4.1.1 on 2022-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_aduino_devicer"),
    ]

    operations = [
        migrations.AddField(
            model_name="aduino",
            name="useridx",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
