# Generated by Django 4.1.1 on 2022-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_aduino_useridx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aduino", name="nowtemp", field=models.IntegerField(null=True),
        ),
    ]
