# Generated by Django 4.1.1 on 2022-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0004_alter_aduino_nowtemp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aduino", name="nowhum", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="aduino", name="nowillum", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="aduino",
            name="nowwaterCycle",
            field=models.IntegerField(null=True),
        ),
    ]
