# Generated by Django 4.1.1 on 2022-10-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farm", "0008_alter_aduino_useridx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aduino",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aduino",
            name="devicer",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aduino",
            name="nowhum",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aduino",
            name="nowillum",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aduino",
            name="nowtemp",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aduino", name="nowwaterCycle", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="aduino", name="useridx", field=models.IntegerField(),
        ),
    ]
